### ISSUE TITLE
Замечания по отчету "Исследование стабильности привязки локальной системы координат БПЛА Клевер‐3"

### ISSUE THREAD

**Issue by sergmin** [DRONE520/CLEVER3#2]
Замечания по отчету "Исследование стабильности привязки локальной системы координат БПЛА Клевер‐3":
1.  Отсутствует описание сценариев при проведении экспериментов "Первый полет", "Второй полет", "Третий полет".
2.  Результаты проведения экспериментов приведены в странных "Усл. единицах". Что это? Выше в документе говорится о координатах в м.
3. При обсуждении экспериментов говорили о том, что объективным показателем ухода координат будет фактическое отклонения координаты точки посадки от координат, полученных от контроллера - ничего этого в отчете нет.
4. Таблицы в Wiki вполне можно добавить штатным образом, см.:[Creating a table](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-tables).
5. Отсутствуют ссылки на публикации и WEB-ресурсыю
6. Разработанные программы не размещены в репозитории https://github.com/DRONE520/CLEVER3/

**Comment by EkimovP** [comment]
Данной темой занимаюсь я и Скороходов Егор. Потапов Артём занимается СПО бортовой системы захвата и сопровождения цели.

**Comment by sergmin** [comment]
Ошибка. Исправил

**Comment by EkimovP** [comment]
Добавлены ссылки на публикации и WEB-ресурсы.

**Comment by EkimovP** [comment]
Поправили отчёт: поменялись таблицы и рисунки, добавили пункт в вывод, добавили описание сценариев. Разработанная программа размещена в репозитории: https://github.com/DRONE520/CLEVER3/

**Comment by EkimovP** [comment]
Добавлена таблица №4 и графики. Сделаны выводы по данным таблицы

**Comment by EkimovP** [comment]
Надо ли полностью добавлять таблицу №4 в отчёт? Она занимает 8 страниц.

**Comment by EkimovP** [comment]
Ещё необходимо индивидуальное задание, завтра перед защитой его получить нам?

**Comment by sergmin** [comment]
1 Таблица №4 не помешает, даже если она занимает 8 стр.
2 Наречие "некорректно" пишется слитно.
3 Подготовлю индивидуальные задания и завтра раздам.

**Comment by EkimovP** [comment]
хорошо
